### ISSUE TITLE
Could not find module `ember-cli-link-tags/index`

### ISSUE THREAD

**Issue by jamemackson** [tomasbasham/ember-cli-link-tags#1]
I installed this addon in a fairly basic ember app and got this error after following the directions to add a basic head link to a route.

```
Uncaught Error: Could not find module `ember-cli-link-tags/index` imported from `ember-cli-link-tags`
```

This is while using ember-cli 1.13.8, 
ember version: 2.0.2
node: 4.1.1
npm: 2.13.4
os: darwin x64

**Comment by jamemackson** [comment]
ok I realized this is just an error in the import statement called for in the documentation.  It should instead be `import Linkable from 'ember-cli-link-tags/mixins/linkable';` and it works fine.  I'll submit a PR later this evening to correct this in the docs.

**Comment by tomasbasham** [comment]
That's a great spot. Thank you
